CREATE TABLE IF NOT EXISTS ThongTinDangNhap (
    MaTKDN INT AUTO_INCREMENT PRIMARY KEY,
    MaKH INT NOT NULL UNIQUE,
    MatKhauHash VARCHAR(255) NOT NULL,
    NgayTao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_thongtindangnhap_khachhang
        FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);